name: Push workflow

on: [push]

jobs:
    build:
      runs-on: macos-latest  # Changed to macOS runner

      steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' # Checkout submodules recursively
          token: ${{ secrets.MY_GITHUB_TOKEN_FOR_PRIVATE_REPOS }}
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'
    
      - name: Export Python path
        run: echo "PYTHON_PATH=$(which python)" >> $GITHUB_ENV

      - name: Install CMake
        run: brew install cmake  # Changed to brew for macOS

      - name: Install Bazel
        run: |
          brew tap bazelbuild/tap
          brew install bazelbuild/tap/bazel

      - name: Cache pipenv virtual environment
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
  
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
  
      - name: Install dependencies with pipenv 
        run: |
          pipenv install --verbose
  
      - name: Test with pytest using pipenv
        run: |
          pipenv run pytest tests/

      # - name: Test with pytest using pipenv, excluding tests/cpp/PyMatching
      #   run: |
      #     pipenv run pytest tests/ --ignore=tests/cpp/PyMatching
