name: Push workflow

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' # Checkout submodules recursively
          token: ${{ secrets.MY_GITHUB_TOKEN_FOR_PRIVATE_REPOS }}
  
      - name: Install CMake
        run: sudo apt-get install -y cmake
  
      - name: Build C++ package
        run: |
          cmake .
          make
  
      - name: Install local qiskit_qec package
        run: pip install ./libs/qiskit-qec
        
      - name: Cache pipenv virtual environment
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
  
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
  
      - name: Install dependencies with pipenv
        run: |
          pipenv install --dev
  
      - name: Test with pytest using pipenv
        run: |
          pipenv run pytest/tests
  