name: Push workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build C++ package
      run: |
        cmake .
        make

    - name: Install local qiskit_qec package
      run: pip install ./libs/qiskit-qec
      
    - name: Cache pipenv virtual environment
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies with pipenv
      run: |
        pipenv install --dev

    - name: Test with pytest using pipenv
      run: |
        pipenv run pytest/tests